// Command syso regenerates the Windows resource objects (app icon + manifest +
// version info) that the Go linker embeds into SuperVibe.exe.
//
// It mirrors Wails' own compileResources() (pkg/commands/build/packager.go) so
// a plain `go build` produces byte-for-byte the same resources as `wails build`:
//
//	icon      build/windows/icon.ico             (Wails derives this from build/appicon.png)
//	manifest  build/windows/wails.exe.manifest   ({{.Name}} / {{.Info.*}} resolved)
//	version   build/windows/info.json            ({{.Info.*}} resolved)
//
// Where it deliberately differs from Wails: Wails emits a single
// <Name>-res.syso for whichever GOARCH it is currently building, then deletes
// it. This writes one object per architecture up front, named
// <Name>-res_windows_<arch>.syso, so the Go linker auto-selects the object that
// matches GOARCH (a <Name>_windows_arm64.syso is ignored by an amd64 link and
// vice versa).
//
// The objects are written to build/windows/, NOT the package root. Two .rsrc
// sections in a single link fail with "too many .rsrc sections", which is
// exactly what happens if a committed object sits next to the one Wails writes
// during `wails build`. build.ps1 / .air.toml copy the matching object into the
// package root only for the duration of a plain `go build`.
//
// Usage:
//
//	go run ./tools/syso            # both architectures
//	go run ./tools/syso -archs 386 # explicit set (amd64, arm64, 386)
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/tc-hib/winres"
	"github.com/tc-hib/winres/version"
)

// wailsConfig is the subset of wails.json this tool reads.
type wailsConfig struct {
	Name           string `json:"name"`
	OutputFilename string `json:"outputfilename"`
	Info           struct {
		CompanyName    string  `json:"companyName"`
		ProductName    string  `json:"productName"`
		ProductVersion string  `json:"productVersion"`
		Copyright      *string `json:"copyright"`
		Comments       *string `json:"comments"`
	} `json:"info"`
}

// assetData mirrors the template context Wails hands to build/windows files.
type assetData struct {
	Name           string
	Info           interface{}
	OutputFilename string
}

var archs = map[string]winres.Arch{
	"amd64": winres.ArchAMD64,
	"arm64": winres.ArchARM64,
	"386":   winres.ArchI386,
}

func main() {
	archList := flag.String("archs", "amd64,arm64", "comma separated list: amd64, arm64, 386")
	flag.Parse()

	root, err := projectRoot()
	if err != nil {
		fatal(err)
	}

	cfg, err := loadConfig(filepath.Join(root, "wails.json"))
	if err != nil {
		fatal(err)
	}

	rs, err := buildResourceSet(root, cfg)
	if err != nil {
		fatal(err)
	}

	for _, name := range strings.Split(*archList, ",") {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		arch, ok := archs[name]
		if !ok {
			fatal(fmt.Errorf("unsupported arch %q (want amd64, arm64 or 386)", name))
		}
		out := filepath.Join(root, "build", "windows", cfg.Name+"-res_windows_"+name+".syso")
		if err := writeObject(out, rs, arch); err != nil {
			fatal(err)
		}
		fmt.Printf("wrote %s\n", rel(root, out))
	}
}

// buildResourceSet reproduces Wails' compileResources resource-for-resource.
func buildResourceSet(root string, cfg *wailsConfig) (*winres.ResourceSet, error) {
	rs := winres.ResourceSet{}

	// Icon. build/windows/icon.ico is generated by Wails from build/appicon.png
	// (256/128/64/48/32/16) the first time it is missing; from then on it is the
	// source of truth, so it is what ends up in the .exe and the taskbar.
	icoFile, err := os.Open(filepath.Join(root, "build", "windows", "icon.ico"))
	if err != nil {
		return nil, err
	}
	defer icoFile.Close()

	ico, err := winres.LoadICO(icoFile)
	if err != nil {
		return nil, fmt.Errorf("couldn't load icon from icon.ico: %w", err)
	}
	if err := rs.SetIcon(winres.RT_ICON, ico); err != nil {
		return nil, err
	}

	// Manifest.
	manifestData, err := resolveFile(root, cfg, "windows", "wails.exe.manifest")
	if err != nil {
		return nil, err
	}
	xmlData, err := winres.AppManifestFromXML(manifestData)
	if err != nil {
		return nil, err
	}
	rs.SetManifest(xmlData)

	// Version info.
	versionRaw, err := resolveFile(root, cfg, "windows", "info.json")
	if err != nil {
		return nil, err
	}
	if len(bytes.TrimSpace(versionRaw)) != 0 {
		var vi version.Info
		if err := vi.UnmarshalJSON(versionRaw); err != nil {
			return nil, err
		}
		rs.SetVersionInfo(vi)
	}

	return &rs, nil
}

func writeObject(out string, rs *winres.ResourceSet, arch winres.Arch) error {
	f, err := os.Create(out)
	if err != nil {
		return err
	}
	defer f.Close()
	return rs.WriteObject(f, arch)
}

// resolveFile reads build/<dir>/<name> and expands the {{...}} placeholders with
// the same context Wails uses (Name, Info, OutputFilename).
func resolveFile(root string, cfg *wailsConfig, dir, name string) ([]byte, error) {
	content, err := os.ReadFile(filepath.Join(root, "build", dir, name))
	if err != nil {
		return nil, err
	}

	funcMap := template.FuncMap{
		"xml":          xmlEscape,
		"safeBundleID": safeBundleID,
	}
	tmpl, err := template.New(name).Funcs(funcMap).Parse(string(content))
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg.templateData()); err != nil {
		return nil, fmt.Errorf("unable to resolve %s: %w", name, err)
	}
	return buf.Bytes(), nil
}

func loadConfig(path string) (*wailsConfig, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg wailsConfig
	if err := json.Unmarshal(raw, &cfg); err != nil {
		return nil, err
	}

	// Defaults copied from Wails' internal/project (Name, OutputFilename, Info).
	if cfg.Name == "" {
		cfg.Name = "wailsapp"
	}
	if cfg.OutputFilename == "" {
		cfg.OutputFilename = cfg.Name
	}
	if !strings.HasSuffix(cfg.OutputFilename, ".exe") {
		cfg.OutputFilename += ".exe"
	}
	if cfg.Info.CompanyName == "" {
		cfg.Info.CompanyName = cfg.Name
	}
	if cfg.Info.ProductName == "" {
		cfg.Info.ProductName = cfg.Name
	}
	if cfg.Info.ProductVersion == "" {
		cfg.Info.ProductVersion = "1.0.0"
	}
	if cfg.Info.Copyright == nil {
		v := "Copyright........."
		cfg.Info.Copyright = &v
	}
	if cfg.Info.Comments == nil {
		v := "Built using Wails (https://wails.io)"
		cfg.Info.Comments = &v
	}
	return &cfg, nil
}

func (c *wailsConfig) templateData() *assetData {
	return &assetData{
		Name:           c.Name,
		Info:           c.Info,
		OutputFilename: c.OutputFilename,
	}
}

func projectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "wails.json")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("couldn't find wails.json in %s or any parent", dir)
		}
		dir = parent
	}
}

func xmlEscape(s string) string {
	var buf bytes.Buffer
	template.HTMLEscape(&buf, []byte(s))
	return buf.String()
}

var nonAlphaNum = regexp.MustCompile(`[^A-Za-z0-9]+`)

func safeBundleID(s string) string {
	result := strings.ToLower(nonAlphaNum.ReplaceAllString(s, "-"))
	return strings.Trim(result, "-")
}

func rel(root, path string) string {
	r, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return r
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "syso:", err)
	os.Exit(1)
}
